[build-system]
requires = ["setuptools>=62", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "gen-utils"
dynamic = ["version"]
dependencies = [
    "numpy",
    "scipy"
]


[tool.setuptools]
packages=["gen_utils"]

[tool.setuptools_scm]